language: rust
sudo: false
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
install:
- curl https://nodejs.org/dist/v0.12.7/node-v0.12.7-sunos-x64.tar.gz > node.tar.gz
- tar xf node.tar.gz
- export PATH=$PATH:$pwd/node-v0.12.7-linux-x64/bin
script:
- rustc --version
- make
- make test
- make html
notifications:
  email:
  - shaposhnikigor95@bk.ru
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
branches:
  only: master
env:
  global:
  - secure: OKU2d3B+LDSFok3SFzSnw1CAmmN0G9PW1sylW8UDMk/l24V1ol1w8EpewEXyhqIa4+KYjOoVDR87E82xBvlW+b1rdAzgFjh22GCtzulySYfHZqOdKLVChmEyKhKnmgXwqehSk8+KQkaRWc2qNVBhLXbgNDcZWyP2QgSIftBjCS1NkBdaLgQ5LOeTuFLMaJHfKmy5iv9mh5Jcn21faBA9J1f1BA1Y8y210AnnIqTfvqoba5702IEWfZCXec+rL9pKlTynJndevKRLEgzuLiQViHs9gd/rgf0bmAq1zxswbn2YIvI+CD0USuLXv7RxEk2dKEOpt5kSaMkbeNCRSDKhmGwv/5ucH5EUeXA2KuKgkJM49r6qhoo9OcTKX/Co+jKSLCNv0/gkcXmvV+JJGRxArAK508hMkxoYsW4r4287GgkbRhzOyejwUnaFkDYx1xbNMYall3pbnqhOp1Vb8afXoEBa3ASg0aY0GObdHZ/Flv8djbeh0MOHQiDHDAyTtynir2c/MVgV1Vglhrehg9NiwBZgyufOkxRk7rn61phpDSDy7M0TAURaW7ByXESFDwP2MJ2SnuMpCbdC5m0VtX4u65hniOWykfIWILpTCsBtzxS5xub4ND8gmIHgIY782eN8aq5GvWT6sG4DHV/hZN/JpQdGMJIlWCf0/aR9Eu1ptI0=
